apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/omni
generators:
  - ../../../../../helm/overlays/dev/cluster/omni
  - generate-cluster-config.yaml