apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: omnictl-apply-job
  namespace: omni-system
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - args:
        - |-
          /tmp/apply-changes.sh ||
          sleep infinity
        command:
        - /bin/sh
        - -c
        env:
        - name: OMNI_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: omniEndpoint
              name: omni-api-key
        - name: OMNI_SERVICE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              key: omniServiceAccountKey
              name: omni-api-key
        image: ghcr.io/dajrivera/omnictl:v0.49.1
        name: omnictl-apply-delete
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /omni
          name: omni
        - mountPath: /tmp/apply-changes.sh
          name: omni-scripts
          subPath: apply-changes.sh
      initContainers:
      - args:
        - |-
          /tmp/check-changes.sh ||
          sleep infinity
        command:
        - /bin/sh
        - -c
        env:
        - name: HOME
          value: /omni
        image: docker.io/alpine/git:v2.47.2
        name: clone-source-repo
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /omni
          name: omni
        - mountPath: /tmp/check-changes.sh
          name: omni-scripts
          subPath: check-changes.sh
        workingDir: /omni
      restartPolicy: Never
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: Always
      volumes:
      - emptyDir:
          sizeLimit: 500Mi
        name: omni
      - configMap:
          defaultMode: 364
          items:
          - key: check-changes.sh
            path: check-changes.sh
          - key: apply-changes.sh
            path: apply-changes.sh
          name: omni-scripts
        name: omni-scripts
