apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: omni-cluster
name: omni-cluster
chartHome: charts
releaseName: omni-cluster
namespace: omni-system
includeCRDs: true
skipHooks: false